E0000 = "Language Configuration not recognized"
E0001 = "Unable to read Vocab file, [file not found or file is corrupted]"
E0002 = "Unable to read Document file"
E0003 = "Unable to read Encoding file"
E0004 = "Unable to write Document file"
E0005 = "Unable to write Encoding file"
E0006 = "Unable to load transformer model"
E0007 = "Unable transform sentence to encodings"
E0008 = "Unable to write Reference file"
EHTTP0404 = "Resource not found or body payload is not in the correct format."