E0000 = "Language Configuration not recognized"
E0001 = "Unable to read Vocab file, [file not found or file is corrupted]"
E0002 = "Unable to read Catalogue file"
E0003 = "Unable to read Embedding file"
E0004 = "Unable to write Catalogue file"
E0005 = "Unable to write Embedding file"
E0006 = "Unable to load transformer model"
E0007 = "Unable transform sentence to embeddings"
E0008 = "Unable to write Reference file"
E0009 = "Catalogue not found in memory"
E0010 = "Law not found in memory"
E0011 = "Unable to find text of Law"
E0012 = "Unable to create file of Law"
EHTTP0404 = "Resource not found or body payload is not in the correct format."